version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "5001:5001"
      - "9229:9229" # Expose debugger
    depends_on: []
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge

volumes: {}
